arch: ResNet50
aug: true  ############## think ob this!!
batch_size: 512  # Two batches are made, so this will be x2 
ckpt: ''
color_dist_s: 1.0
config_file: ''
data: ROV
dist: dp
dist_address: '198.176.97.88' # changed to bens remote machine
eval_freq: 30
gpu: 1 ################# changed from 0 
iters: 5400 # num batches seen, not epochs! So 1 epoch. 54000/512 = 105.5 iters per epoch
log_freq: 5
lr: 0.6  # was 0.6 default
lr_schedule: warmup-anneal
multiplier: 2
name: ROV
node_rank: 0
opt: lars
problem: sim-clr
root: ''
save_freq: 300
scale_lower: 0.6 # for the crop transform, the min % of the og image to retain. Was 0.08.
seed: -1
sync_bn: true
temperature: 0.1
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 8
world_size: 1
